dd-agent/datadog-agent-7.71.2-1.x86_64.rpm:
  size: 165401504
  object_id: aba2bbdc-e46e-4ba8-7fb4-df6b05e65a89
  sha: sha256:50e64aaf628e0247830e839a72307ecfceacf3734afca0eb1de56abefdc5efa3
dd-agent/datadog-agent_7.71.2-1_amd64.deb:
  size: 162951806
  object_id: 8506f4d1-f441-46e8-6c06-392338925e42
  sha: sha256:0e5b96e7782bb9ae1ecf2b004513dd3b70eda64b86b9c1fbf4f3a71938f16246
